# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.cache/wt [current_project]
set_property parent.project_path E:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:usb104-a7:part0:1.3 [current_project]
set_property ip_repo_paths {
  e:/DOCS/ARM/AT426-r0p1-00rel0-1/AT426-BU-98000-r0p1-00rel0/vivado/Arm_ipi_repository
  e:/DOCS/ARM/AT472-r0p1-00rel0-1/AT472-BU-98000-r0p1-00rel0/vivado/Arm_ipi_repository
} [current_project]
set_property ip_output_repo e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/hdl/ARM_MCU_wrapper.v
add_files E:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ARM_MCU.bd
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_CORTEXM3_AXI_0_0/ARM_MCU_CORTEXM3_AXI_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_clk_wiz_0_0/ARM_MCU_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_clk_wiz_0_0/ARM_MCU_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_clk_wiz_0_0/ARM_MCU_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_rst_clk_wiz_0_50M_0/ARM_MCU_rst_clk_wiz_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_rst_clk_wiz_0_50M_0/ARM_MCU_rst_clk_wiz_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_rst_clk_wiz_0_50M_0/ARM_MCU_rst_clk_wiz_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_proc_sys_reset_0_0/ARM_MCU_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_proc_sys_reset_0_0/ARM_MCU_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_proc_sys_reset_0_0/ARM_MCU_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_xbar_0/ARM_MCU_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_axi_bram_ctrl_0_0/ARM_MCU_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_axi_bram_ctrl_0_bram_0/ARM_MCU_axi_bram_ctrl_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_axi_uartlite_0_0/ARM_MCU_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_axi_uartlite_0_0/ARM_MCU_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_axi_uartlite_0_0/ARM_MCU_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_auto_pc_0/ARM_MCU_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_auto_pc_2/ARM_MCU_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_auto_pc_1/ARM_MCU_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ARM_MCU_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/constrs_1/new/usb104_a7.xdc
set_property used_in_implementation false [get_files E:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/constrs_1/new/usb104_a7.xdc]

read_xdc E:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/constrs_1/new/timing_usb104_a7.xdc
set_property used_in_implementation false [get_files E:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/constrs_1/new/timing_usb104_a7.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top ARM_MCU_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ARM_MCU_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ARM_MCU_wrapper_utilization_synth.rpt -pb ARM_MCU_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
