# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/usb104_a7.xdc

# XDC: new/timing_usb104_a7.xdc

# Block Designs: bd/ARM_MCU/ARM_MCU.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU || ORIG_REF_NAME==ARM_MCU} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_CORTEXM3_AXI_0_0/ARM_MCU_CORTEXM3_AXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_CORTEXM3_AXI_0_0 || ORIG_REF_NAME==ARM_MCU_CORTEXM3_AXI_0_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_clk_wiz_0_0/ARM_MCU_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_clk_wiz_0_0 || ORIG_REF_NAME==ARM_MCU_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_rst_clk_wiz_0_50M_0/ARM_MCU_rst_clk_wiz_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_rst_clk_wiz_0_50M_0 || ORIG_REF_NAME==ARM_MCU_rst_clk_wiz_0_50M_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_proc_sys_reset_0_0/ARM_MCU_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_proc_sys_reset_0_0 || ORIG_REF_NAME==ARM_MCU_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_util_vector_logic_0_0/ARM_MCU_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_util_vector_logic_0_0 || ORIG_REF_NAME==ARM_MCU_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_xlconstant_0_0/ARM_MCU_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_xlconstant_0_0 || ORIG_REF_NAME==ARM_MCU_xlconstant_0_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_util_vector_logic_1_0/ARM_MCU_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_util_vector_logic_1_0 || ORIG_REF_NAME==ARM_MCU_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_util_vector_logic_2_0/ARM_MCU_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_util_vector_logic_2_0 || ORIG_REF_NAME==ARM_MCU_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_util_vector_logic_3_0/ARM_MCU_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_util_vector_logic_3_0 || ORIG_REF_NAME==ARM_MCU_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_util_vector_logic_4_0/ARM_MCU_util_vector_logic_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_util_vector_logic_4_0 || ORIG_REF_NAME==ARM_MCU_util_vector_logic_4_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_util_vector_logic_5_0/ARM_MCU_util_vector_logic_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_util_vector_logic_5_0 || ORIG_REF_NAME==ARM_MCU_util_vector_logic_5_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_axi_interconnect_0_0/ARM_MCU_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_axi_interconnect_0_0 || ORIG_REF_NAME==ARM_MCU_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_xbar_0/ARM_MCU_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_xbar_0 || ORIG_REF_NAME==ARM_MCU_xbar_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_xlconstant_1_0/ARM_MCU_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_xlconstant_1_0 || ORIG_REF_NAME==ARM_MCU_xlconstant_1_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_axi_bram_ctrl_0_0/ARM_MCU_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_axi_bram_ctrl_0_0 || ORIG_REF_NAME==ARM_MCU_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_axi_bram_ctrl_0_bram_0/ARM_MCU_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==ARM_MCU_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_axi_uartlite_0_0/ARM_MCU_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_axi_uartlite_0_0 || ORIG_REF_NAME==ARM_MCU_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_tri_io_buf_0_0/ARM_MCU_tri_io_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_tri_io_buf_0_0 || ORIG_REF_NAME==ARM_MCU_tri_io_buf_0_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_auto_pc_0/ARM_MCU_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_auto_pc_0 || ORIG_REF_NAME==ARM_MCU_auto_pc_0} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_auto_pc_2/ARM_MCU_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_auto_pc_2 || ORIG_REF_NAME==ARM_MCU_auto_pc_2} -quiet] -quiet

# IP: bd/ARM_MCU/ip/ARM_MCU_auto_pc_1/ARM_MCU_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_MCU_auto_pc_1 || ORIG_REF_NAME==ARM_MCU_auto_pc_1} -quiet] -quiet

# XDC: bd/ARM_MCU/ARM_MCU_ooc.xdc
