# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_proc_sys_reset_0_0/ARM_MCU_proc_sys_reset_0_0.xci
# IP: The module: 'ARM_MCU_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_proc_sys_reset_0_0/ARM_MCU_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARM_MCU_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_proc_sys_reset_0_0/ARM_MCU_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARM_MCU_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_proc_sys_reset_0_0/ARM_MCU_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARM_MCU_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_proc_sys_reset_0_0/ARM_MCU_proc_sys_reset_0_0.xci
# IP: The module: 'ARM_MCU_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_proc_sys_reset_0_0/ARM_MCU_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARM_MCU_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_proc_sys_reset_0_0/ARM_MCU_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARM_MCU_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/SW/Vivado_Projetcs/ARM_CM3_A7/ARM_CM3_A7.srcs/sources_1/bd/ARM_MCU/ip/ARM_MCU_proc_sys_reset_0_0/ARM_MCU_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARM_MCU_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
